### ISSUE TITLE
Proxy dans le yarn.lock

### ISSUE THREAD

**Issue by michaelchiche** [ShakurOo/meilleursagents#1]
On ne peut pas installer sans supprimer le `yarn.lock` parce que ca pointe vers un registry prive

**Comment by ShakurOo** [comment]
Oh my bad je vais corrigé ça merci pour le retour !

**Comment by ShakurOo** [comment]
PS: En attendant tu peux toujours `rm yarn.lock` et refaire une fresh install, j'utilise pas vraiment de private package. Les liens présents dans le fichier .lock sont dus à la configuration de mon `.npmrc` local. Par défaut je pointe sur le registry privée de prisma qui fait proxy sur le registry d'npm, même pour les packages non privés ...

**Comment by michaelchiche** [comment]
Oui., c’est ce que j’ai fait.

**Comment by ShakurOo** [comment]
C'est fixé ^^ merci !
